Develop pc bv1.0 mme301
lardc/hw-LCTUControlBoard pull request #2
Opened 2022-08-12 07:24 UTC by IvanovDmtr

2022-08-12 12:40 UTC, asytyi requested changes

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +#include "SelfTest.h"
Файла нет в проекте

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Controller.h
> +	SS_ST_PulseCheck = 14
```suggestion
	SS_ST_Sync = 10,
	SS_ST_StartPulse,
	SS_ST_Pulse,
	SS_ST_WaitPause,
	SS_ST_PulseCheck
```
В TrueStudio для enum'ов удобно указывать номер только первой записи в группе. Остальные автоматом нумеруются и их значение подсвечивается при наведении курсора. Удобно при добавлении новых состояний, чтобы всё не перенумеровывать и при этом числа отражали последовательность этих состояний.

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/ConvertUtils.c
> +		MeasureVParams.B = (Int16S)DataTable[REG_ADC_V_R0_B] / 10;
Здесь и в других местах обращения к регистрам DT надо поправить преобразование типов с учётом того, что DT уже float

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_REGULATOR_ALOWED_ERR		31	// Допустимая ошибка регулирования (% * 10)
Здесь и для остальных подобных мест убрать ненужные умножения на 10

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		DataTable[REG_OP_RESULT] = OPRESULT_FAIL;
Приоритетным для ПО верхнего уровня является состояние блока. Если блок в fault или disabled, то обращение к OP_RESULT не происходит. И так понятно, что всё сломалось. Поэтому OP_RESULT можно не трогать и он останется NONE.
Если блок после измерения в Ready, то считывается OP_RESULT для определения можно ли обращаться к регистрам результата. Если OP_RESULT OK, то можно считывать результат. Если по каким-то причинам измерение завершено некорректно, то OP_RESULT FAIL. В этом случае регистры результата содержат 0, и должен быть выставлен регистр PROBLEM на указание причины некорректного завершения измерения, например принудительная остановка.

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
>  	{
В обработчике ACT_STOP_PROCESS не происходит сброс хардварной периферии в состояние по умолчанию. Так же должен выставляться OP_RESULT_FAIL (см. комментарий ниже)

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Logic.c
> +		*Fault = DF_SAFETY;
Логика остановки формирования по срабатыванию контура безопасности должна быть такой же как и при принудительной остановке с помощью команды (см. комментарии в Controller.c) и не приводить к фолту.

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Logic.c
> +			*Fault = DF_FOLLOWING_ERROR;
Выставление Fault должно быть только при обнаружении внутренней аппаратной неисправности в блоке. Потому что при считывании состояния Fault ПО верхнего уровня прервёт все измерения и выключит все блоки. В текущей логике срабатывание FollowingError не гарантирует, что что-то в блоке сломалось. Например, попался закороченный прибор. Выйти на заданное напряжение не получится, но ведь сам LCTU нормально работает.
Единственный признак аппаратной неисправности самого LCTU это то, что он не может выйти на заданное напряжение и при этом через DUT не течёт ток.
А если, например, LCTU просто упёрся в отсечку по току и поэтому не может держать полку напряжения, то здесь надо подумать как лучше поступать. Я вижу два варианта:
- вернуть Problem перегрузки выхода и нулевые значения в регистрах результата
- вернуть фактически измеренные значения тока и напряжения с выставлением Warning'а об обнаружении перегрузки

2022-08-12 12:40 UTC, asytyi commented on Firmware/Source/Controller/Logic.c
> +		CONTROL_ValuesCurrent[LocalCounter] = (Int16U)(Sample.Current);
EP тоже надо перевести во флоатовские, чтобы не заниматься ненужным умножением

2022-08-12 12:43 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +#include "SelfTest.h"
Добавил

2022-08-12 12:46 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.h
> +	SS_ST_PulseCheck = 14
Поправил

2022-08-12 12:53 UTC, IvanovDmtr commented on Firmware/Source/Controller/ConvertUtils.c
> +		MeasureVParams.B = (Int16S)DataTable[REG_ADC_V_R0_B] / 10;
Готово

2022-08-12 12:59 UTC, IvanovDmtr commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_REGULATOR_ALOWED_ERR		31	// Допустимая ошибка регулирования (% * 10)
Готово

2022-08-15 07:11 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +		DataTable[REG_OP_RESULT] = OPRESULT_FAIL;
Убрал этот кусок кода

2022-08-15 07:18 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
>  	{
Доработал

2022-08-15 07:25 UTC, IvanovDmtr commented on Firmware/Source/Controller/Logic.c
> +		*Fault = DF_SAFETY;
Доработал

2022-08-15 09:10 UTC, IvanovDmtr commented on Firmware/Source/Controller/Logic.c
> +			*Fault = DF_FOLLOWING_ERROR;
Доработал

2022-08-15 09:37 UTC, IvanovDmtr commented on Firmware/Source/Controller/Logic.c
> +		CONTROL_ValuesCurrent[LocalCounter] = (Int16U)(Sample.Current);
Доработал

2025-07-22 08:48 UTC, closed without merging